// Typed access to the bundled safe-deployments table (generated by scripts/gen-safe-deployments.ts).
import type { Address, Hex } from 'viem'
import data from '@/generated/safe-deployments.json'
import type { DeploymentTables, ProxyInfo, SingletonInfo } from './authenticity'

interface ContractInfo {
  readonly contractName: string
  readonly version: string
  readonly variant: string
  readonly address: Address
  readonly codeHash: Hex
}

export const deployments = data as unknown as DeploymentTables & {
  readonly source: { readonly repo: string; readonly tag: string; readonly commit: string }
  readonly supportedVersions: readonly string[]
  readonly singletons: readonly (SingletonInfo & { readonly address: Address })[]
  readonly proxies: readonly ProxyInfo[]
  readonly multiSend: readonly ContractInfo[]
  readonly multiSendCallOnly: readonly ContractInfo[]
  readonly simulateTxAccessor: readonly ContractInfo[]
  readonly deployBlocks: Readonly<Record<string, Readonly<Record<string, string>>>>
}

const matches = (list: readonly ContractInfo[], codeHash: Hex) =>
  list.find((c) => c.codeHash.toLowerCase() === codeHash.toLowerCase())

/** A MultiSend or MultiSendCallOnly verified by code hash (SPEC §4.2, §7.4). */
export const findMultiSend = (codeHash: Hex) =>
  matches(deployments.multiSendCallOnly, codeHash) ?? matches(deployments.multiSend, codeHash)

export const findSimulateTxAccessor = (codeHash: Hex) =>
  matches(deployments.simulateTxAccessor, codeHash)
