// Safe's GSxxx revert codes, from safe-smart-account docs/error_codes.md (v1.3.0, v1.4.1, v1.5.0).
export const GS_ERRORS: Record<string, string> = {
  GS000: 'Could not finish initialization',
  GS001: 'Threshold needs to be defined',
  GS002:
    "A call to set up modules couldn't be executed because the destination account was not a contract",
  GS010: 'Not enough gas to execute the Safe transaction',
  GS011: 'Could not pay gas costs with ether',
  GS012: 'Could not pay gas costs with token',
  GS013: 'The Safe transaction failed (reported this way when gasPrice and safeTxGas are 0)',
  GS020: 'Signatures data too short',
  GS021: 'Invalid contract signature location: inside static part',
  GS022: 'Invalid contract signature location: length not present',
  GS023: 'Invalid contract signature location: data not complete',
  GS024: 'Invalid contract signature provided',
  GS025: 'Hash has not been approved',
  GS026:
    'Invalid owner provided: a signature is not from an owner, is for a different transaction, or signatures are out of order',
  GS027: 'Data hash and hash of the pre-image data do not match',
  GS030: 'Only owners can approve a hash',
  GS031: 'Method can only be called from this contract',
  GS100: 'Modules have already been initialized',
  GS101: 'Invalid module address provided',
  GS102: 'Module has already been added',
  GS103: 'Invalid prevModule, module pair provided',
  GS104: 'Method can only be called from an enabled module',
  GS105: 'Invalid starting point for fetching paginated modules',
  GS106: 'Invalid page size for fetching paginated modules',
  GS200: 'Owners have already been set up',
  GS201: 'Threshold cannot exceed owner count',
  GS202: 'Threshold needs to be greater than 0',
  GS203: 'Invalid owner address provided',
  GS204: 'Address is already an owner',
  GS205: 'Invalid prevOwner, owner pair provided',
  GS300: 'Transaction guard does not implement IERC165',
  GS301: 'Module guard does not implement IERC165',
  GS400: 'Fallback handler cannot be set to self',
}
